# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from model_logic.protos import model_service_pb2 as model__logic_dot_protos_dot_model__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in model_logic/protos/model_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """─── Service Definition ──────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadAdapter = channel.unary_unary(
                '/model_service.ModelService/LoadAdapter',
                request_serializer=model__logic_dot_protos_dot_model__service__pb2.LoadAdapterRequest.SerializeToString,
                response_deserializer=model__logic_dot_protos_dot_model__service__pb2.LoadAdapterResponse.FromString,
                _registered_method=True)
        self.UnloadAdapter = channel.unary_unary(
                '/model_service.ModelService/UnloadAdapter',
                request_serializer=model__logic_dot_protos_dot_model__service__pb2.UnloadAdapterRequest.SerializeToString,
                response_deserializer=model__logic_dot_protos_dot_model__service__pb2.UnloadAdapterResponse.FromString,
                _registered_method=True)
        self.Prefill = channel.unary_unary(
                '/model_service.ModelService/Prefill',
                request_serializer=model__logic_dot_protos_dot_model__service__pb2.PrefillRequest.SerializeToString,
                response_deserializer=model__logic_dot_protos_dot_model__service__pb2.PrefillResponse.FromString,
                _registered_method=True)
        self.Decode = channel.unary_unary(
                '/model_service.ModelService/Decode',
                request_serializer=model__logic_dot_protos_dot_model__service__pb2.DecodeRequest.SerializeToString,
                response_deserializer=model__logic_dot_protos_dot_model__service__pb2.DecodeResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """─── Service Definition ──────────────────────────────────────────────────────

    """

    def LoadAdapter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadAdapter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Prefill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadAdapter,
                    request_deserializer=model__logic_dot_protos_dot_model__service__pb2.LoadAdapterRequest.FromString,
                    response_serializer=model__logic_dot_protos_dot_model__service__pb2.LoadAdapterResponse.SerializeToString,
            ),
            'UnloadAdapter': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadAdapter,
                    request_deserializer=model__logic_dot_protos_dot_model__service__pb2.UnloadAdapterRequest.FromString,
                    response_serializer=model__logic_dot_protos_dot_model__service__pb2.UnloadAdapterResponse.SerializeToString,
            ),
            'Prefill': grpc.unary_unary_rpc_method_handler(
                    servicer.Prefill,
                    request_deserializer=model__logic_dot_protos_dot_model__service__pb2.PrefillRequest.FromString,
                    response_serializer=model__logic_dot_protos_dot_model__service__pb2.PrefillResponse.SerializeToString,
            ),
            'Decode': grpc.unary_unary_rpc_method_handler(
                    servicer.Decode,
                    request_deserializer=model__logic_dot_protos_dot_model__service__pb2.DecodeRequest.FromString,
                    response_serializer=model__logic_dot_protos_dot_model__service__pb2.DecodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_service.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_service.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """─── Service Definition ──────────────────────────────────────────────────────

    """

    @staticmethod
    def LoadAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_service.ModelService/LoadAdapter',
            model__logic_dot_protos_dot_model__service__pb2.LoadAdapterRequest.SerializeToString,
            model__logic_dot_protos_dot_model__service__pb2.LoadAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadAdapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_service.ModelService/UnloadAdapter',
            model__logic_dot_protos_dot_model__service__pb2.UnloadAdapterRequest.SerializeToString,
            model__logic_dot_protos_dot_model__service__pb2.UnloadAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Prefill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_service.ModelService/Prefill',
            model__logic_dot_protos_dot_model__service__pb2.PrefillRequest.SerializeToString,
            model__logic_dot_protos_dot_model__service__pb2.PrefillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_service.ModelService/Decode',
            model__logic_dot_protos_dot_model__service__pb2.DecodeRequest.SerializeToString,
            model__logic_dot_protos_dot_model__service__pb2.DecodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
